# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCjkh8TIwrW_cqybE_FYJibZvgkvJb_G

# **Importing Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""# **Uploading Data**"""

df=pd.read_csv('/content/data.csv')

"""# **Exploring Data**"""

df.head(10)

df.describe()

df.info()

df.shape

df.isnull().sum()

df.dtypes

"""# **Question_Driven Visualization**

#  Which neighborhood has the most expensive houses?
"""

city_price=df.groupby('city')['price'].mean().sort_values(ascending=False)
plt.figure(figsize=(15,10))
sns.barplot(x=city_price.index,y=city_price.values,palette='crest')
plt.xlabel('City')
plt.ylabel('Price')
plt.xticks(rotation=90)
plt.title('City vs Price')
plt.show()

"""**The City with highest average house price is Medina which indicates that it is the most expensive area in the dataset**

---



---

# House_Condition Vs House Price
"""

plt.figure(figsize=(15,10))

sns.barplot(x='condition',y='price',data=df)
plt.xticks(rotation=90)
plt.title('Condition vs Price')
plt.show()

"""**Houses with better condition generally have higher average prices**

---



---

# Water_View Vs Prices
"""

plt.figure(figsize=(15,10))

sns.barplot(x='waterfront',y='price',data=df,palette='crest')
plt.xticks(rotation=90)
sns.set_style('whitegrid')
sns.set_context('talk')
plt.xticks(rotation=90)
plt.title('waterfront vs Price')
plt.show()

"""**Houses With Water View have higher prices than the others with No Water View**

---



---

# Does Living Area Affect house prices or Not ?
"""

plt.figure(figsize=(8,6))

sns.scatterplot(x='sqft_living',y='price',data=df)
plt.title('living Area vs Price')
plt.xlabel('living_Area')
plt.ylabel('price')
plt.show()

"""**larger living Areas generally have higher prices**

---



---

# **Feature Engineering**

Data has no null values
"""

df = df[df['price'] > 0]

df = df[df['price'] < df['price'].quantile(0.995)]


df = df.drop(['date', 'street', 'country', 'statezip'], axis=1)


df = pd.get_dummies(df, columns=['city'], drop_first=True)

"""# **Splitting Data and determining Features and Target**"""

x=df.drop(['price'],axis=1)
y=df['price']

"""# **Spliting Data into Training and Testing Data**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""# **Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

"""# **Modeling & Evaluation**"""

from  sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(x_train,y_train)

y_predict = model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score
MSE=mean_squared_error(y_test,y_predict)
R2=r2_score(y_test,y_predict)
print('MSE:',MSE)
print('R2:',R2)